### ISSUE TITLE
Pleeease stopped working since few days

### ISSUE THREAD

**Issue by lmaze** [iamvdo/pleeease#47]
Hello,

First of all thank you for your project. Pleeease is a great tool and we are more teams to use it in our work.

We recently installed the 3.2.0 version of Pleeease and we have a problem when we use it. Other people had installed this version before and there was no problem with the same configuration. Sounds like a problem with dependencies of Pleeease.

We all have the following error:
```
C:\project>pleeease compile
module.js:338
    throw err;
          ^
Error: Cannot find module 'deep-extend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Users\adm\AppData\Roaming\npm\node_modules\pleeease-cli\lib\cli.js:9:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
We use NodeJs in the 12.0 x64 version. We tried to install the 3.2.1 and 3.2.3 versions of Pleeease but the problem is still there.

Do you have an idea of the problem?

**Comment by lmaze** [comment]
I just installed the latest version of Pleeease with a new fresh installation of NodeJs and the problem is still the same.

**Comment by iamvdo** [comment]
Fixed https://github.com/iamvdo/pleeease-cli/commit/11378f604174fb4d4166ac385a248f42b8451459
I omit to add deep-extend as a dependency (only as a dev dependency). Sorry for that. ;)
