### ISSUE TITLE
Needs to be updated to NodeJs 4.0.0

### ISSUE THREAD

**Issue by nexflo** [iamvdo/pleeease#60]
node-sass & fsevents dependencies need updates.

**Comment by nexflo** [comment]
ah ok, just saw theres a tested pending pull-request already:
https://github.com/iamvdo/pleeease/pull/59

lets get this into master :)

**Comment by iamvdo** [comment]
Planned for next release. Hope it will be released soon.

**Comment by yaycmyk** [comment]
Also to add on this, `postcss-url` needs to be updated. The 3.x.x branch has a nested dependency of `img-stats` which is outdated based on the version of `directory-encoder` used in that series of releases.

It's currently at 5.0.0.

**Comment by iamvdo** [comment]
Fixed in pleeease@4.0.0

**Comment by nexflo** [comment]
Yeah, awesome,thanks! :+1:

**Comment by iamvdo** [comment]
Test it before congratulate me. I've made many changes. Hope everything will be OK. ;)

**Comment by yaycmyk** [comment]
@iamvdo Looks like there's an incompatibility with `pleeease-cli`:

```

/Users/esj/code/uikit/node_modules/pleeease-cli/lib/cli.js:53
    if (this.pleeease.options.sourcemaps) {
                             ^

TypeError: Cannot read property 'sourcemaps' of undefined
    at new CLI (/Users/esj/code/uikit/node_modules/pleeease-cli/lib/cli.js:53:30)
    at new cli (/Users/esj/code/uikit/node_modules/pleeease-cli/lib/cli.js:269:12)
    at Object.<anonymous> (/Users/esj/code/uikit/node_modules/pleeease-cli/bin/pleeease-compile:13:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by iamvdo** [comment]
Yep, needs to be updated too.

**Comment by nexflo** [comment]
Hmm still get:Error: Error: `libsass` bindings not found. Try reinstalling `node-sass`?
on 4.0.0 hmm
